complete -c ffanim -f
complete -c ffanim -l anim -x -a 'sweep wave pulse bounce glitch ripple' -d 'animation, saved'
complete -c ffanim -l color -x -d 'r,g,b at full brightness, saved'
complete -c ffanim -l setup -d 'start ffanim from your shell config'
complete -c ffanim -l unsetup -d 'take that block back out'
complete -c ffanim -l status -d 'what is set, and which file starts it'
complete -c ffanim -l pin -d 'pin above the prompt'
complete -c ffanim -l unpin -d 'stop a pinned painter'
complete -c ffanim -l wrap -d 'run your shell inside ffanim'
complete -c ffanim -l once -d 'print one static frame'
complete -c ffanim -l stdin -d 'read the info pane from stdin'
complete -c ffanim -l off -d 'print the block but skip the animation'
complete -c ffanim -l on -d 'animate again'
complete -c ffanim -l fps -x -d 'frames per second'
complete -c ffanim -l step -x -d 'rows the band moves per frame'
complete -c ffanim -l refresh -x -d 're-read the info pane every n seconds'
complete -c ffanim -l uninstall -d 'delete ffanim and its logo'
complete -c ffanim -l version -d 'print the version'
complete -c ffanim -s h -l help -d 'usage'
